In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('swiggy_vs_zomato_enriched.csv')

In [3]:
df.head()

,restaurant_id,restaurant_name,city,locality,latitude,longitude,restaurant_type,cuisines,top_selling_dish,distance_from_city_center_km,...,amenities_count,seating_capacity_note,loyalty_program,sustainability_packaging_rating,has_own_website,has_own_app,food_license_verified,year_established,listing_date,days_listed
0,REST000001,Tandoor House,Chennai,Velachery,13.11092,80.16023,Cloud Kitchen,Fast Food; Continental,Fries,0.5,...,6,"Delivery-only, no seating",True,4,False,False,False,2021,2024-09-17,671
1,REST000002,Copper Deck,Delhi,Mayur Vihar,28.80022,77.12131,QSR (Quick Service),Thai,Thai Basil Fried Rice,5.4,...,3,Dine-in available,False,2,False,False,True,2014,2019-08-17,2529
2,REST000003,The Fast House,Ahmedabad,Satellite,22.99754,72.49951,Casual Dining,Fast Food,Cheese Sandwich,6.0,...,4,Dine-in available,False,2,False,False,True,2018,2023-06-06,1140
3,REST000004,Urban Bowl,Chennai,Perambur,13.04000,80.27945,Cafe,Korean; Cafe,Korean Fried Chicken,5.1,...,4,Dine-in available,False,2,False,False,True,2016,2018-10-16,2834
4,REST000005,Golden Kitchen Co.,Mumbai,Lower Parel,19.13642,72.94463,Food Truck,Seafood,Prawn Curry,17.6,...,2,"Delivery-only, no seating",False,5,False,True,False,2016,2019-01-27,2731

In [4]:
df.describe()

,latitude,longitude,distance_from_city_center_km,operating_days_per_week,seating_capacity,swiggy_rating,swiggy_total_reviews,zomato_rating,zomato_total_reviews,average_rating_both_platforms,...,swiggy_estimated_monthly_revenue_inr,zomato_estimated_monthly_revenue_inr,swiggy_estimated_net_profit_inr,zomato_estimated_net_profit_inr,swiggy_market_share_pct,zomato_market_share_pct,amenities_count,sustainability_packaging_rating,year_established,days_listed
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,...,8.000000e+03,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,19.944546,77.031232,6.068800,6.655500,46.227000,4.371725,1491.641625,4.373325,1491.142750,4.372525,...,1.391339e+05,138058.163375,106608.882375,105726.849625,49.989700,50.010300,4.989625,2.982625,2018.563250,1829.255875
std,5.449833,4.013453,4.035941,0.567768,39.675011,0.380041,782.091824,0.378403,771.773246,0.363931,...,9.043824e+04,86828.431729,69694.140146,66588.328965,8.651764,8.651764,1.988407,1.416801,3.388869,1044.736090
min,12.815340,72.376990,0.200000,5.000000,0.000000,2.900000,218.000000,2.900000,180.000000,3.000000,...,1.197000e+04,11712.000000,8882.000000,9236.000000,20.500000,18.100000,2.000000,1.000000,2011.000000,30.000000
25%,13.220012,73.747280,3.100000,6.000000,0.000000,4.100000,894.000000,4.100000,901.000000,4.150000,...,7.628350e+04,77786.500000,58151.000000,59231.000000,44.100000,44.000000,3.000000,2.000000,2016.000000,915.750000
50%,19.047095,77.127450,5.200000,7.000000,44.000000,4.400000,1345.000000,4.400000,1345.000000,4.400000,...,1.168355e+05,116607.000000,89584.000000,89278.500000,50.000000,50.000000,5.000000,3.000000,2019.000000,1833.500000
75%,23.057630,78.463063,8.200000,7.000000,81.000000,4.700000,1928.250000,4.700000,1935.250000,4.650000,...,1.769992e+05,174602.750000,135042.500000,134712.250000,56.000000,55.900000,7.000000,4.000000,2021.000000,2743.250000
max,28.857860,88.513440,22.000000,7.000000,120.000000,5.000000,6651.000000,5.000000,6212.000000,5.000000,...,1.049517e+06,914008.000000,829696.000000,653415.000000,81.900000,79.500000,8.000000,5.000000,2026.000000,3649.000000

In [6]:
df.info

<bound method DataFrame.info of      restaurant_id             restaurant_name       city         locality  \
0       REST000001               Tandoor House    Chennai        Velachery
1       REST000002                 Copper Deck      Delhi      Mayur Vihar
2       REST000003              The Fast House  Ahmedabad        Satellite
3       REST000004                  Urban Bowl    Chennai         Perambur
4       REST000005          Golden Kitchen Co.     Mumbai      Lower Parel
...            ...                         ...        ...              ...
7995    REST007996  The Vietnamese Express (4)  Bangalore  Electronic City
7996    REST007997         Copper Street Tadka     Mumbai            Dadar
7997    REST007998   Harvest Continental Grill      Delhi        Paharganj
7998    REST007999           Sunrise Point (5)  Bangalore      Indiranagar
7999    REST008000      Barrel Kitchen Co. (3)     Jaipur        Jagatpura

      latitude  longitude      restaurant_type                   cuisines  \
0     13.11092   80.16023        Cloud Kitchen     Fast Food; Continental
1     28.80022   77.12131  QSR (Quick Service)                       Thai
2     22.99754   72.49951        Casual Dining                  Fast Food
3     13.04000   80.27945                 Cafe               Korean; Cafe
4     19.13642   72.94463           Food Truck                    Seafood
...        ...        ...                  ...                        ...
7995  13.00280   77.58861        Cloud Kitchen                 Vietnamese
7996  19.07009   72.94246  QSR (Quick Service)  Street Food; South Indian
7997  28.66471   77.01837        Casual Dining                Continental
7998  12.93367   77.57301           Food Truck                  Pan-Asian
7999  26.94135   75.77994            Fine Dine                    Mughlai

           top_selling_dish  distance_from_city_center_km  ...  \
0                     Fries                           0.5  ...
1     Thai Basil Fried Rice                           5.4  ...
2           Cheese Sandwich                           6.0  ...
3      Korean Fried Chicken                           5.1  ...
4               Prawn Curry                          17.6  ...
...                     ...                           ...  ...
7995                    Pho                           9.9  ...
7996              Pani Puri                           6.4  ...
7997        Grilled Chicken                           1.6  ...
7998                Dim Sum                           5.7  ...
7999                 Nihari                           1.9  ...

     amenities_count      seating_capacity_note  loyalty_program  \
0                  6  Delivery-only, no seating             True
1                  3          Dine-in available            False
2                  4          Dine-in available            False
3                  4          Dine-in available            False
4                  2  Delivery-only, no seating            False
...              ...                        ...              ...
7995               8  Delivery-only, no seating            False
7996               2          Dine-in available            False
7997               2          Dine-in available             True
7998               5  Delivery-only, no seating            False
7999               5          Dine-in available             True

      sustainability_packaging_rating  has_own_website  has_own_app  \
0                                   4            False        False
1                                   2            False        False
2                                   2            False        False
3                                   2            False        False
4                                   5            False         True
...                               ...              ...          ...
7995                                3            False         True
7996                                5             True        False
7997                                2             True        False
7998                                4             True        False
7999                                1             True        False

      food_license_verified  year_established  listing_date  days_listed
0                     False              2021    2024-09-17          671
1                      True              2014    2019-08-17         2529
2                      True              2018    2023-06-06         1140
3                      True              2016    2018-10-16         2834
4                     False              2016    2019-01-27         2731
...                     ...               ...           ...          ...
7995                   True              2018    2020-03-09         2324
7996                  False              2021    2025-11-03          259
7997                   True              2011    2016-08-05         3636
7998                   True              2016    2019-07-05         2572
7999                   True              2018    2019-04-17         2651

[8000 rows x 55 columns]>

In [10]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'city', 'locality', 'latitude',
       'longitude', 'restaurant_type', 'cuisines', 'top_selling_dish',
       'distance_from_city_center_km', 'opening_time', 'closing_time',
       'operating_days_per_week', 'seating_capacity', 'swiggy_rating',
       'swiggy_total_reviews', 'zomato_rating', 'zomato_total_reviews',
       'average_rating_both_platforms', 'customer_sentiment_score',
       'avg_cost_per_person_inr', 'price_category', 'swiggy_delivery_fee_inr',
       'zomato_delivery_fee_inr', 'swiggy_avg_delivery_time_minutes',
       'zomato_avg_delivery_time_minutes', 'avg_prep_time_minutes',
       'swiggy_platform_commission_pct', 'zomato_platform_commission_pct',
       'swiggy_discount_frequency_pct', 'zomato_discount_frequency_pct',
       'swiggy_estimated_monthly_orders', 'zomato_estimated_monthly_orders',
       'monthly_order_growth_pct', 'weekend_order_uplift_pct',
       'repeat_customer_pct', 'online_order_share_pct',
       'swiggy_estimated_monthly_revenue_inr',
       'zomato_estimated_monthly_revenue_inr',
       'swiggy_estimated_net_profit_inr', 'zomato_estimated_net_profit_inr',
       'swiggy_market_share_pct', 'zomato_market_share_pct',
       'platform_performance_better', 'amenities', 'amenities_count',
       'seating_capacity_note', 'loyalty_program',
       'sustainability_packaging_rating', 'has_own_website', 'has_own_app',
       'food_license_verified', 'year_established', 'listing_date',
       'days_listed'],
      dtype='object')

In [12]:
df=df[['restaurant_name','city','cuisines', 'swiggy_rating',
       'swiggy_total_reviews', 'zomato_rating', 'zomato_total_reviews','avg_cost_per_person_inr','price_category', 'swiggy_delivery_fee_inr',
       'zomato_delivery_fee_inr', 'swiggy_avg_delivery_time_minutes','zomato_avg_delivery_time_minutes','swiggy_estimated_monthly_orders', 'zomato_estimated_monthly_orders','swiggy_estimated_monthly_revenue_inr',
       'zomato_estimated_monthly_revenue_inr','repeat_customer_pct',  'platform_performance_better']]

In [13]:
print(df)

                 restaurant_name       city                   cuisines  \
0                  Tandoor House    Chennai     Fast Food; Continental
1                    Copper Deck      Delhi                       Thai
2                 The Fast House  Ahmedabad                  Fast Food
3                     Urban Bowl    Chennai               Korean; Cafe
4             Golden Kitchen Co.     Mumbai                    Seafood
...                          ...        ...                        ...
7995  The Vietnamese Express (4)  Bangalore                 Vietnamese
7996         Copper Street Tadka     Mumbai  Street Food; South Indian
7997   Harvest Continental Grill      Delhi                Continental
7998           Sunrise Point (5)  Bangalore                  Pan-Asian
7999      Barrel Kitchen Co. (3)     Jaipur                    Mughlai

      swiggy_rating  swiggy_total_reviews  zomato_rating  \
0               4.0                  1480            3.7
1               3.9                  3025            4.1
2               3.9                   877            4.2
3               4.6                  1390            4.8
4               4.6                   768            4.8
...             ...                   ...            ...
7995            4.3                  2539            3.8
7996            4.1                   866            4.1
7997            3.5                  1581            3.6
7998            4.9                  2633            4.6
7999            4.0                   757            4.1

      zomato_total_reviews  avg_cost_per_person_inr price_category  \
0                      706                      310      Mid-Range
1                     3100                      146         Budget
2                     1350                      650      Mid-Range
3                      735                      551      Mid-Range
4                     1678                      311      Mid-Range
...                    ...                      ...            ...
7995                  1258                      242         Budget
7996                  1114                      247         Budget
7997                  1565                      709        Premium
7998                  1414                      215         Budget
7999                  1127                     1904         Luxury

      swiggy_delivery_fee_inr  zomato_delivery_fee_inr  \
0                          15                       22
1                          41                       41
2                          38                       45
3                          44                       35
4                          98                      101
...                       ...                      ...
7995                       69                       67
7996                       46                       44
7997                       26                       28
7998                       40                       48
7999                       21                       27

      swiggy_avg_delivery_time_minutes  zomato_avg_delivery_time_minutes  \
0                                   18                                19
1                                   23                                27
2                                   23                                32
3                                   24                                27
4                                   41                                48
...                                ...                               ...
7995                                31                                33
7996                                32                                30
7997                                23                                23
7998                                29                                29
7999                                18                                26

      swiggy_estimated_monthly_orders  zomato_estimated_monthly_orders  \
0                                 252                              341
1                                 367                              487
2                                 176                              179
3                                 266                              270
4                                 207                              312
...                               ...                              ...
7995                              389                              265
7996                              246                              255
7997                              284                              259
7998                              339                              187
7999                              109                              130

      swiggy_estimated_monthly_revenue_inr  \
0                                    78120
1                                    53582
2                                   114400
3                                   146566
4                                    64377
...                                    ...
7995                                 94138
7996                                 60762
7997                                201356
7998                                 72885
7999                                207536

      zomato_estimated_monthly_revenue_inr  repeat_customer_pct  \
0                                   105710                   54
1                                    71102                   42
2                                   116350                   50
3                                   148770                   67
4                                    97032                   61
...                                    ...                  ...
7995                                 64130                   50
7996                                 62985                   47
7997                                183631                   30
7998                                 40205                   67
7999                                247520                   42

     platform_performance_better
0                  Zomato Better
1                  Zomato Better
2                  Swiggy Better
3                       Balanced
4                  Zomato Better
...                          ...
7995               Swiggy Better
7996               Zomato Better
7997               Swiggy Better
7998               Swiggy Better
7999               Zomato Better

[8000 rows x 19 columns]

In [14]:
df.isnull().sum()

restaurant_name                         0
city                                    0
cuisines                                0
swiggy_rating                           0
swiggy_total_reviews                    0
zomato_rating                           0
zomato_total_reviews                    0
avg_cost_per_person_inr                 0
price_category                          0
swiggy_delivery_fee_inr                 0
zomato_delivery_fee_inr                 0
swiggy_avg_delivery_time_minutes        0
zomato_avg_delivery_time_minutes        0
swiggy_estimated_monthly_orders         0
zomato_estimated_monthly_orders         0
swiggy_estimated_monthly_revenue_inr    0
zomato_estimated_monthly_revenue_inr    0
repeat_customer_pct                     0
platform_performance_better             0
dtype: int64

In [16]:
df.dtypes

restaurant_name                          object
city                                     object
cuisines                                 object
swiggy_rating                           float64
swiggy_total_reviews                      int64
zomato_rating                           float64
zomato_total_reviews                      int64
avg_cost_per_person_inr                   int64
price_category                           object
swiggy_delivery_fee_inr                   int64
zomato_delivery_fee_inr                   int64
swiggy_avg_delivery_time_minutes          int64
zomato_avg_delivery_time_minutes          int64
swiggy_estimated_monthly_orders           int64
zomato_estimated_monthly_orders           int64
swiggy_estimated_monthly_revenue_inr      int64
zomato_estimated_monthly_revenue_inr      int64
repeat_customer_pct                       int64
platform_performance_better              object
dtype: object

In [18]:
df['city'].value_counts()

city
Mumbai       1471
Bangalore    1377
Delhi        1195
Pune          816
Hyderabad     761
Chennai       625
Kolkata       553
Ahmedabad     515
Jaipur        378
Lucknow       309
Name: count, dtype: int64

In [19]:
df['cuisines'].value_counts()

cuisines
Lebanese                   215
Street Food                204
Biryani                    202
Pan-Asian                  201
Thai                       200
                          ...
Street Food; Vietnamese      2
Street Food; Mexican         2
Chinese; Fast Food           2
Korean; Seafood              2
Vietnamese; Korean           2
Name: count, Length: 528, dtype: int64

In [21]:
df['swiggy_rating'].mean()

np.float64(4.3717250000000005)

In [22]:
df['zomato_rating'].mean()

np.float64(4.3733249999999995)

In [23]:
df['swiggy_avg_delivery_time_minutes'].mean()

np.float64(27.687)

In [24]:
df['zomato_avg_delivery_time_minutes'].mean()

np.float64(28.30375)

In [25]:
df['swiggy_estimated_monthly_revenue_inr'].mean()

np.float64(139133.8805)

In [26]:
df['zomato_estimated_monthly_revenue_inr'].mean()

np.float64(138058.163375)

In [27]:
df['swiggy_estimated_monthly_orders'].mean()

np.float64(271.67725)

In [28]:
df['zomato_estimated_monthly_orders'].mean()

np.float64(271.566125)

In [29]:
df['swiggy_delivery_fee_inr'].mean()

np.float64(45.560375)

In [30]:
df['zomato_delivery_fee_inr'].mean()

np.float64(44.38175)

In [36]:
df.groupby('city')[['swiggy_estimated_monthly_orders','zomato_estimated_monthly_orders']].mean()

           swiggy_estimated_monthly_orders  zomato_estimated_monthly_orders
city
Ahmedabad                       219.708738                       224.617476
Bangalore                       289.273784                       285.514887
Chennai                         286.110400                       294.369600
Delhi                           294.221757                       292.320502
Hyderabad                       293.014455                       286.545335
Jaipur                          215.600529                       220.650794
Kolkata                         289.235081                       291.251356
Lucknow                         217.844660                       219.809061
Mumbai                          289.026513                       288.267165
Pune                            214.000000                       215.566176

In [38]:
df.groupby('city')[['swiggy_estimated_monthly_revenue_inr','zomato_estimated_monthly_revenue_inr']].mean()

,swiggy_estimated_monthly_revenue_inr,zomato_estimated_monthly_revenue_inr
city,,
Ahmedabad,112527.223301,114862.077670
Bangalore,147596.379085,144774.935367
Chennai,145453.633600,147053.068800
Delhi,156127.405021,153727.654393
Hyderabad,147702.607096,142901.308804
Jaipur,106308.378307,109527.150794
Kolkata,152502.978300,153413.222423
Lucknow,111366.404531,111487.893204
Mumbai,146102.804895,144803.759347
Pune,108025.363971,107721.539216

In [40]:
df.to_csv('cleaned_zomato_vs_swiggy.csv')